export const getTasksRoute = () => '/'
export const getNewTaskRoute = () => '/new-task'
export const getSignUpRoute = () => '/sign-up'
export const getSignInRoute = () => '/sign-in'
export const getSignOutRoute = () => '/sign-out'
